### PR TITLE
Type definitions for Parity POE

### PR DESCRIPTION
**Pull request by leovujanic**
Added type definitions for Parity POE so that this module can be used in TypeScript.

### CODE REVIEW

**Comment by leovujanic** [comment]
Hi @jvirtanen , I finally managed to find the time to make updates on this. My apologies for the delay. 

I have a question regarded `BROKEN_TRADE` option. It's available in library and tests but I can't find it in the documentation nor in java code. Is it possible to receive that kind of message from the Parity system?

**Comment by jvirtanen** [comment]
Thank you, @leovujanic!

Well spotted; Broken Trade was indeed part of the protocol prior to Parity 0.7.0, but it was removed in Parity 0.7.0. Would you like to open another pull request to clean up all remnants of it from this library? 🙂 If you are busy, I can also do that myself. After that, I'll release new versions of all three Node libraries. :+1:

**Comment by leovujanic** [comment]
@jvirtanen I will be glad to do it. :)
Is there anything else except things related to broken trade message that needs to be removed? I'm not sure if `ORDER_CANCEL_REASON_SUPERVISORY` is used somewhere and should I keep it?

**Comment by jvirtanen** [comment]
I think the Broken Trade message is the only thing awaiting immediate removal right now. Although Parity does not currently send `ORDER_CANCEL_REASON_SUPERVISORY`, it's still part of the protocol. In the future, it could be used e.g. for self-trade prevention. 🙂

**Pull request merged**
